/* ************************************************************************** */
/*                                                                            */
/*                                                        ::::::::            */
/*   yeet.h                                             :+:    :+:            */
/*                                                     +:+                    */
/*   By: tbruinem <tbruinem@student.codam.nl>         +#+                     */
/*                                                   +#+                      */
/*   Created: 2020/09/25 13:24:14 by tbruinem      #+#    #+#                 */
/*   Updated: 2020/09/25 17:22:14 by tbruinem      ########   odam.nl         */
/*                                                                            */
/* ************************************************************************** */

#ifndef YEET_H
# define YEET_H

#include <stddef.h>

size_t	ft_strrlenrevs(char *str, char rstart, char rend, char *set);
void	ft_strrev(char *str);
char	*ft_stradd(char *str, char *add);
size_t	ft_numlenu_base(unsigned int num, int base);
size_t	ft_strrlenrevc(char *str, char rstart, char rend, char c);
char	*ft_strnump(char *str, int *val);
char	*ft_strnadd(char *str, char *add, size_t n);
char	*ft_strnstr(char *str, char *ndl, size_t n);
size_t	ft_strnskipw(char *str, size_t len);
size_t	ft_strnskips(char *str, size_t len, char *set);
char	*ft_strdups(char *str, char *set);
size_t	ft_strnskipr(char *str, size_t len, char rstart, char rend);
size_t	ft_strnlens(char *str, size_t n, char *set);
size_t	ft_strnlenb(char *str, size_t n);
size_t	ft_strnlen(char *str, size_t n);
size_t	ft_strncat(char *dst, char *src, size_t len);
char	*ft_strndup(char *str, size_t n);
size_t	ft_strnlenrevc(char *str, long n, char c);
size_t	ft_strlen(char *str);
char	*ft_strsdup(char *str, char *set);
char	*ft_strdup(char *str);
void	ft_str2print(char **str);
char	**ft_lstconvstr2(t_list *root);
size_t	ft_strlenc(char *str, char c);
void	ft_str2prefix(char **str, char *prefix);
size_t	ft_strslenrevs(char *str, char *set, char *set2);
size_t	ft_strcpy(char *dst, char *src);
size_t	ft_strskipr(char *str, char rstart, char rend);
size_t	ft_strclens(char *str, char c, char *set);
size_t	ft_strclenrevr(char *str, char stop, char rstart, char rend);
size_t	ft_strrlen(char *str, char rstart, char rend);
int	ft_chrcprint(char c, char nope);
size_t	ft_strclenrev(char *str, char c);
size_t	ft_strrlenb(char *str, char rstart, char rend);
size_t	ft_strclenr(char *str, char c, char rstart, char rend);
size_t	ft_strclenc(char *str, char c, char match);
char	*ft_strchr(char *str, char c);
void	debug(t_pfconv *conv);
char	*ft_strchain(char **str);
char	*ft_strcdups(char *str, char c, char *set);
char	*ft_numstrul_base(unsigned long num, char *base, size_t minimum);
char	*ft_strcdup(char *str, char c);
size_t	ft_strcatc(char *dst, char c);
size_t	ft_strcat(char *dst, char *src);
char	*ft_strblockrevget(char *str, char *delim, size_t index);
char	*ft_straddr(char *str, char rstart, char rend);
char	*ft_strchaindelimc(char **str, char delim);
char	*ft_straddn(char *str, size_t n);
void	ft_dlistaddinfront(t_dlist *elem, t_dlist *add);
char	*ft_straddc(char *str, char c);
void	ft_str2suffix(char **str, char *suffix);
int	ft_chrprint(char c);
void	*ft_plstnew(void *item, int priority);
void	*ft_stkpop(t_list **list);
void	ft_plstsuffix(t_plist **list, t_plist *add);
size_t	ft_strclenb(char *str, char c);
size_t	ft_strlenr(char *str, char rstart, char rend);
void	*ft_pquepop(t_plist **list);
int	vec_nullterm(t_vec *vec);
void	*ft_memcpy(void *dst, void *src, size_t len);
char	*ft_strprefix(char *str, char *prefix);
size_t	ft_strrlenrev(char *str, char rstart, char rend);
void	ft_dlstclearright(t_dlist **head, t_dlist *elem, void (*f)(void *item));
void	ft_lstprefix(t_list **list, t_list *add);
char	*ft_numstru_base(unsigned int num, char *base, size_t minimum);
int	ft_printf(char *arguments);
t_list	*ft_lstlookup(t_list *root, char *str);
void	ft_memmove(void *dst, void *src, size_t n);
char	*program_end(t_pfdata *data, int *ret);
size_t	ft_memslen(void *mem, char *set, size_t n);
size_t	ft_strlens(char *str, char *set);
size_t	ft_strnskip(char *str, size_t len);
char	**ft_strcsplit(char *str, char c);
long long	ft_str2cmpstr(char **str2, char *str);
size_t	ft_strmatchc(char *str, char c);
size_t	ft_strwlen(char *str);
size_t	ft_strlenw(char *str);
int	conv_chr(t_pfdata *data, t_pfconv *conv);
void	ft_strnprint(char *str, size_t n);
void	ft_numprintbase(int nb, int base);
char	*numpadding(char *num, t_pfconv *conv, int len);
char	*ft_strdupc(char *str, char c);
int	ft_fdchar(int fd, char *c);
void	ft_dlstdel(t_dlist **head, t_dlist *del, void (*f)(void *item));
size_t	ft_strslenrev(char *str, char *set);
int	conv_ulong(t_pfdata *data, t_pfconv *conv);
char	*ft_sprintf(int *ret, char *arguments);
size_t	ft_strscat(char *dst, char *src, char *set);
size_t	ft_strnlenrevs(char *str, long n, char *set);
void	ft_chrswapc(char *a, char *b);
size_t	ft_strscpy(char *dst, char *src, char *set);
HEAP	*ft_memcdup(void *mem, size_t n, char c);
char	*ft_strsep(char *str, char *delimiter);
size_t	ft_strnskipc(char *str, size_t len, char c);
size_t	ft_strwlens(char *str, char *set);
char	*ft_strtok(char *str, char *delimiter);
void	ft_treeaddparent(t_tree **root, t_tree *add);
void	ft_treeaddchild(t_tree *branch, t_tree *add);
void	ft_treeprint(t_tree *root, void (*print)(void *item));
char	*ft_strstr(char *str, char *ndl);
void	ft_strshift(char *str, long long shift);
size_t	ft_strwlenrevc(char *str, char c);
void	ft_treeaddleft(t_tree *branch, t_tree *add);
void	*vec_getref(t_vec *vec, size_t index);
size_t	ft_strskipc(char *str, char c);
size_t	ft_strslenrevr(char *str, char *set, char rstart, char rend);
size_t	ft_strwlenc(char *str, char c);
char	ft_chrmatchw(char c);
t_tree	*ft_treebfirst(t_tree *root, int (*f)(void *item, void *cmp), t_list *queue, void *cmp);
void	*ft_pstkpop(t_plist **list);
int	ft_chrprintfdc(char c, char yes, int fd);
char	*ft_strsuffix(char *str, char *suffix);
int	vec_realloc(t_vec *vec, size_t amount);
size_t	ft_strwlenr(char *str, char rstart, char rend);
void	ft_strwprint(char *str);
char	**ft_strwsplit(char *str, char c);
void	*ft_quepop(t_list **list);
int	vec_destroy(t_vec *vec);
int	ft_chrprintc(char c, char yes);
int	vec_add(t_vec *vec, void *buff, size_t amount);
char	*ft_strwdup(char *str);
void	ft_strtrunc(char *start, size_t size);
size_t	ft_strwlenrevr(char *str, char rstart, char rend);
char	*ft_strtrimsf(char *str, char *set);
char	*ft_strtrims(char *str, char *set);
char	**ft_strssplit(char *str, char *set);
size_t	ft_strncpy(char *dst, char *src, size_t len);
int	parseconv(t_pfdata *data);
t_plist	*ft_plstptr(t_plist *list);
char	*ft_strgenc(char c, size_t len);
int	ft_chrcprintfd(char c, char nope, int fd);
int	vec_new(t_vec *vec, size_t typesize);
size_t	ft_strwlenrevs(char *str, char *set);
size_t	ft_strslenrevc(char *str, char *set, char c);
void	ft_lstprint(t_list *head, void (*p)(char *item));
int	vec_insert(t_vec *vec, void *buff, size_t amount, size_t index);
size_t	ft_strslenc(char *str, char *set, char c);
size_t	ft_strslen(char *str, char *set);
t_tree	*ft_treenew(void *item);
size_t	ft_numlenul_base(unsigned long num, int base);
size_t	ft_strskipw(char *str);
size_t	ft_strslenb(char *str, char *set);
void	ft_lstswap(t_list **list, t_list *a, t_list *b);
t_list	*ft_lstnptr(t_list *list, size_t n);
void	ft_lstsuffix(t_list **list, t_list *add);
void	ft_plstprefix(t_plist **list, t_plist *add);
char	ft_strncmp(char *str, char *s2, size_t n);
t_list	*ft_lstptr(t_list *list);
char	**ft_strnsplit(char *str, size_t n);
t_list	*ft_lstprev(t_list **list, t_list *elem);
int	conv_uint(t_pfdata *data, t_pfconv *conv);
size_t	ft_strnlenr(char *str, size_t n, char rstart, char rend);
char	*ft_strsadd(char *str, char *add, char *set);
void	ft_strconvl(char *str);
int	ft_chrprints(char c, char *set);
int	ft_fdstr2c(int fd, char ***line, char c);
char	ft_chrmatchr(char c, char rstart, char rend);
int	ft_chrprintfds(char c, int fd, char *set);
HEAP	*ft_calloc(size_t size, size_t len);
HEAP	*ft_memdup(void *mem, size_t n);
int	conv_str(t_pfdata *data, t_pfconv *conv);
size_t	ft_numlen_base(int num, int base);
char	*ft_strreplace(char *org, char *before, char *after);
void	ft_str2fmap(char **str, char *(*f)(char *str, char *arg), char *arg);
void	ft_stkpush(t_list **list, void *item);
long long	ft_absnum(long long nb);
size_t	ft_strrlens(char *str, char rstart, char rend, char *set);
int	ft_fdstrc(int fd, char **line, char c);
char	ft_lstcmp(void *a, void *b, char (*cmp)(void *item1, void *item2));
void	ft_lstinfix(t_list **list, t_list *add, size_t n);
void	ft_strreplacec(char *str, char c, char replace);
char	*ft_strinfix(char *dst, char *add, size_t index);
int	ft_chrsprint(char c, char *set);
size_t	ft_str2len(char **str);
char	ft_chrmatchc(char c, char match);
size_t	ft_strclenrevc(char *str, char stop, char c);
size_t	ft_strwlenb(char *str);
void	ft_dlstaddfront(t_dlist **head, t_dlist *add);
size_t	ft_strrlenc(char *str, char rstart, char rend, char c);
char	ft_chrmatchs(char c, char *set);
void	ft_dlistaddbehind(t_dlist *elem, t_dlist *add);
char	*ft_numstr_base(int num, int base, size_t minimum);
void	ft_dlstaddback(t_dlist **head, t_dlist *add);
void	ft_dlstclear(t_dlist **head, void (*f)(void *item));
HEAP	*ft_lstnew(void *item);
long long	ft_nummax(long long a, long long b);
void	ft_strconvu(char *str);
size_t	ft_strnlenrevr(char *str, long n, char rstart, char rend);
void	ft_treeaddright(t_tree *branch, t_tree *add);
HEAP	*ft_dlstnew(void *item, void *prev);
long long	ft_str2ncmpstr(char **str2, char *str);
void	ft_dlstclearleft(t_dlist **head, t_dlist *elem, void (*f)(void *item));
void	ft_lstrev(t_list **list);
void	ft_strprint(void *str);
void	ft_numprint(int nb);
int	conv_di(t_pfdata *data, t_pfconv *conv);
void	ft_str2del(char **str);
size_t	ft_strskips(char *str, char *set);
void	ft_dlstprint(t_dlist **head);
size_t	ft_strwlenrev(char *str);
void	ft_memset(void *mem, size_t len, char c);
size_t	ft_memclen(void *mem, char c, size_t n);
void	ft_dlstswap(t_dlist **head, t_dlist *a, t_dlist *b);
char	**ft_str2dup(char **str);
int	ft_strcmp(void *str1, void *str2);
long long	ft_lstindex(t_list *list, t_list *elem);
size_t	ft_strslenr(char *str, char *set, char rstart, char rend);
void	ft_lstdel(t_list **list, t_list *elem, void (*del)(void *item));
size_t	ft_lstlen(t_list *list);
void	ft_pquepush(t_plist **list, void *item, int priority);
int	ft_chrprintfd(char c, int fd);
size_t	ft_strclenrevs(char *str, char stop, char *set);
void	ft_quepush(t_list **list, void *item);
void	ft_pstkpush(t_plist **list, void *item, int priority);
char	ft_strccmp(char *str, char *s2, char c);
size_t	ft_strclen(char *str, char c);
t_list	*ft_str2convlst(char **str2);
size_t	ft_strnlenc(char *str, size_t n, char match);
size_t	ft_strslens(char *str, char *stop, char *set);

#endif

